### PR TITLE
cart page updated

### PR DESCRIPTION
**Pull request by rr-rana**
I've updated the cart page, if there is no product in the cart it will now show the message " No item added yet ".

### CODE REVIEW

**Comment by Alamgirf12** [comment]
okl

**Comment by rr-rana** [comment]
git ignore updated, now you can merge

**Review by Alamgirf12 — APPROVED** [review]

**Comment by rr-rana** [comment]
everything is okay, Now I can expect to merge

**Review by Alamgirf12 — APPROVED** [review]
ok

**Pull request closed without merging**
